#%RAML 1.0 Library
usage: provides resuable datatypes for card details object

types:
  item:
   type: object
   properties:
     name:
      type: string
      description: name
      maxLength: 30
     quantity:
      type: string
      description: quantity
      maxLength: 10
     price:
      type: string
      description: card_amt
      maxLength: 10
      
