#%RAML 1.0 Library
usage: provides a set of reusable data types that commonly occur in schedule times definitions
types: 
 schedule_times:
  properties:
    preparation_time:
     displayName: preparation_time
     description: 
     type: integer
    scheduled_time:
     displayName: scheduled_time
     description: 
     type: string
     maxLength: 30
     
